garden:
  swagger:
    enable: true
spring:
  application:
    name: garden-cloud-example
  cloud:
    sentinel:
      transport:
        dashboard: 127.0.0.1:9100
      eager: true #取消控制台懒加载
      datasource:
        flow: #数据源名称，可以自定义
          nacos: #nacos配置中心
            #Nacos内置配置中心，因此重用即可
            server-addr: acos.tonyiscoding.top:8848
            dataId: ${spring.application.name}-sentinel-flow #定义流控规则data-id，完整名称为:sentinel-sample-flow-rules，在配置中心设置时data-id必须对应。
            groupId: DEFAULT_GROUP #gourpId对应配置文件分组，对应配置中心groups项
            namespace: d0e8196d-4b75-47d9-9a15-809a59ae7243
            rule-type: flow #flow固定写死，说明这个配置是流控规则
            username: nacos #nacos通信的用户名与密码
            password: nacos

  redis:
    redisson:
      config: |
        singleServerConfig:
          password: dyn8DUbpzRQvrCxn
          address: redis://redis.tonyiscoding.top:6379
          database: 0
          idleConnectionTimeout: 10000
          connectTimeout: 10000
          timeout: 3000
          retryAttempts: 3
          retryInterval: 1500
          subscriptionsPerConnection: 5
          clientName: null
          subscriptionConnectionMinimumIdleSize: 1
          subscriptionConnectionPoolSize: 50
          connectionMinimumIdleSize: 32
          connectionPoolSize: 64
          dnsMonitoringInterval: 5000

        threads: 0
        nettyThreads: 0
        codec: !<org.redisson.codec.JsonJacksonCodec> {}
        transportMode: "NIO"
